---
# Common Role - Ultra Light Version
- name: Install essential packages
  package:
    name: [git, curl, vim, wget, htop]
    state: present
  become: yes

- name: Create common directory
  file:
    path: /opt/common
    state: directory
  become: yes