---
# Common Role - Single File
# Basic system setup and common packages

- name: Common System Setup
  block:
    # Package Installation
    - name: Update package cache (Ubuntu/Debian)
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Update package cache (CentOS/RHEL)
      yum:
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Install common packages (Ubuntu/Debian)
      apt:
        name:
          - git
          - curl
          - vim
          - wget
          - unzip
          - htop
          - net-tools
        state: present
      when: ansible_os_family == "Debian"

    - name: Install common packages (CentOS/RHEL)
      yum:
        name:
          - git
          - curl
          - vim
          - wget
          - unzip
          - htop
          - net-tools
        state: present
      when: ansible_os_family == "RedHat"

    # Directory Setup
    - name: Create common directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /opt/common
        - /var/log/ansible
        - /etc/ansible/facts.d

    # System Configuration
    - name: Set timezone
      timezone:
        name: "{{ system_timezone | default('UTC') }}"

    - name: Configure system limits
      pam_limits:
        domain: '*'
        limit_type: soft
        limit_item: nofile
        value: '65536'

    - name: Display system information
      debug:
        msg: |
          Common setup completed:
          - OS Family: {{ ansible_os_family }}
          - Distribution: {{ ansible_distribution }} {{ ansible_distribution_version }}
          - Architecture: {{ ansible_architecture }}
          - Timezone: {{ system_timezone | default('UTC') }}

  become: yes
  tags: common