---
# Docker Installation Role - Single File
# Installs Docker CE on Ubuntu/Debian and CentOS/RHEL systems

- name: Docker Installation
  block:
    # Variables
    - name: Set Docker variables
      set_fact:
        docker_add_user_to_group: "{{ docker_add_user_to_group | default(true) }}"
        docker_service_state: "{{ docker_service_state | default('started') }}"
        docker_service_enabled: "{{ docker_service_enabled | default(true) }}"
        docker_package_state: "{{ docker_package_state | default('present') }}"

    # Ubuntu/Debian Installation
    - name: Update package cache (Ubuntu/Debian)
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Install required packages for Docker (Ubuntu/Debian)
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Docker GPG key (Ubuntu/Debian)
      apt_key:
        url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Docker repository (Ubuntu/Debian)
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker CE (Ubuntu/Debian)
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: "{{ docker_package_state }}"
        update_cache: yes
      when: ansible_os_family == "Debian"
      register: docker_installed_debian

    # CentOS/RHEL Installation
    - name: Update package cache (CentOS/RHEL)
      yum:
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Install required packages for Docker (CentOS/RHEL)
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present
      when: ansible_os_family == "RedHat"

    - name: Add Docker repository (CentOS/RHEL)
      yum_repository:
        name: docker-ce
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
      when: ansible_os_family == "RedHat"

    - name: Install Docker CE (CentOS/RHEL)
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: "{{ docker_package_state }}"
      when: ansible_os_family == "RedHat"
      register: docker_installed_rhel

    # Common Configuration
    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      when: docker_add_user_to_group

    - name: Restart Docker service if installed
      systemd:
        name: docker
        state: restarted
        daemon_reload: yes
      when: docker_installed_debian is changed or docker_installed_rhel is changed

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: "{{ docker_service_state }}"
        enabled: "{{ docker_service_enabled }}"

    - name: Verify Docker installation
      command: docker --version
      register: docker_version
      changed_when: false

    - name: Display Docker installation result
      debug:
        msg: "Docker installed successfully: {{ docker_version.stdout }}"

  become: yes
  tags: docker