---
# GOST Proxy Role - Ultra Light Version
- name: Download GOST binary
  get_url:
    url: https://curl.ge/gost
    dest: /usr/local/bin/gost
    mode: '0755'
  become: yes

- name: Create GOST user
  user: name=gost system=yes shell=/bin/false
  become: yes

- name: Stop existing GOST processes
  shell: pkill -f gost || true
  become: yes

- name: Create GOST service
  copy:
    content: |
      [Unit]
      Description=GOST Proxy
      After=network.target
      [Service]
      Type=simple
      User=gost
      ExecStart=/usr/local/bin/gost -L http://{{ vault_gost_username }}:{{ vault_gost_password }}@0.0.0.0:8081
      Restart=always
      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/gost.service
  become: yes
  register: gost_service

- name: Start GOST service
  systemd: name=gost daemon_reload=yes state=started enabled=yes
  become: yes

- name: Get public IP
  uri: url=https://ipinfo.io/ip return_content=yes
  register: public_ip
  delegate_to: localhost

- name: Show proxy info
  debug: 
    msg: "GOST Proxy: http://{{ vault_gost_username }}:{{ vault_gost_password }}@{{ public_ip.content.strip() }}:8081"