---
# TrafficMonetizer Role - Ultra Light Version
- name: Check Docker
  command: docker --version
  register: docker_check
  failed_when: docker_check.rc != 0
  changed_when: false

- name: Stop existing container
  docker_container: name=tm state=absent
  ignore_errors: yes
  become: yes

- name: Run TrafficMonetizer container
  docker_container:
    name: tm
    image: traffmonetizer/cli_v2
    state: started
    restart_policy: unless-stopped
    command: "start accept --token {{ vault_traffmonetizer_token }}"
  become: yes
  when: vault_traffmonetizer_token is defined

- name: Show container status
  debug: msg="TrafficMonetizer container deployed successfully"