hosts:
  all:
    hosts:
      host1:
        ansible_host: 192.168.1.10
        ansible_user: user1
      host2:
        ansible_host: 192.168.1.20
        ansible_user: user2
    children:
      webservers:
        hosts:
          host1:
          host2:
      dbservers:
        hosts:
          host3:
          host4: