---
galaxy_info:
  author: your_name
  description: Deploy TrafficMonetizer CLI container
  company: your_company
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - 7
        - 8
        - 9
  galaxy_tags:
    - docker
    - containers
    - traffmonetizer

dependencies:
  - role: docker