---
# tasks file for traffmonetizer role

- name: Check if Docker is installed
  command: docker --version
  register: docker_check
  failed_when: false
  changed_when: false

- name: Fail if Docker is not installed
  fail:
    msg: "Docker is not installed. Please run the docker role first."
  when: docker_check.rc != 0

- name: Pull TrafficMonetizer Docker image
  docker_image:
    name: traffmonetizer/cli_v2
    source: pull
    state: present
  become: yes

- name: Stop existing TrafficMonetizer container if running
  docker_container:
    name: tm
    state: absent
  become: yes
  ignore_errors: yes

- name: Run TrafficMonetizer container
  docker_container:
    name: tm
    image: traffmonetizer/cli_v2
    state: started
    restart_policy: unless-stopped
    detach: yes
    command: "start accept --token {{ traffmonetizer_token }}"
  become: yes
  when: traffmonetizer_token is defined

- name: Verify TrafficMonetizer container is running
  docker_container_info:
    name: tm
  register: container_info
  become: yes

- name: Display container status
  debug:
    msg: "TrafficMonetizer container status: {{ container_info.container.State.Status if container_info.exists else 'Not found' }}"