- name: Ensure common packages are installed
  apt:
    name:
      - git
      - curl
      - vim
    state: present

- name: Create a directory for common files
  file:
    path: /opt/common
    state: directory

- name: Copy configuration file
  template:
    src: my_template.j2
    dest: /etc/my_config.conf

- name: Ensure the service is running
  service:
    name: my_service
    state: started
    enabled: yes