---
# handlers file for gost-proxy role

- name: restart gost
  systemd:
    name: gost
    state: restarted
    daemon_reload: yes
  become: yes

- name: reload gost
  systemd:
    name: gost
    state: reloaded
  become: yes

- name: stop gost
  systemd:
    name: gost
    state: stopped
  become: yes